# Generated by Django 5.1.6 on 2025-03-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_size_product_sizes'),
        ('orders', '0002_order_delivered_order_middle_name_order_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.size'),
        ),
    ]
